# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:
  sawtooth-rest-api:
    image: hyperledger/sawtooth-rest-api
    container_name: sawtooth-rest-api
    expose:
      - 8008
    ports:
      - '8008:8008'
      - '8043:8008'
    depends_on:
      - validator
    entrypoint: |
      sawtooth-rest-api -vv
        --connect tcp://validator:4004
        --bind sawtooth-rest-api:8008

  sawtooth-shell:
    image: hyperledger/sawtooth-shell
    container_name: sawtooth-shell
    volumes:
      - '.:/project/sawtooth-marketplace'
    working_dir: /project/sawtooth-marketplace
    container_name: sawtooth-shell
    depends_on:
      - sawtooth-rest-api
    entrypoint: |
      bash -c "
        if [ ! -f /root/.sawtooth/keys/root.priv ]; then
        sawtooth keygen
        fi;
        tail -f /dev/null
      "
  
  market-shell:
    build:
      context: .
      dockerfile: ./dev_env/Dockerfile-installed
    image: market-dev-env-installed
    container_name: market-shell-installed
    depends_on:
      - market-processor
      - market-ledger-sync
      - market-rest-api
    command: tail -f /dev/null

  market-processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-tp-installed
    container_name: market-tp-installed
    command: marketplace-tp -v -C tcp://validator:4004

  market-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-rest-api-installed
    expose:
      - 8000
    ports:
      - '8040:8000'
    depends_on:
      - market-ledger-sync
      - rethink
      - validator
    command: |
      bash -c "
        sleep 3 &&
        marketplace-rest-api \
          --host market-rest-api \
          --db-host rethink \
          --validator tcp://validator:4004
      "

  market-ledger-sync:
    build:
      context: .
      dockerfile: ./ledger_sync/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-ledger-sync-installed
    container_name: market-ledger-sync-installed
    depends_on:
      - rethink
      - validator
    command: |
      bash -c "
        sleep 1 &&
        market-setup-db --host rethink &&
        marketplace-ledger-sync -vv \
          --db-host rethink \
          --validator tcp://validator:4004
      "

  market-sawbuck-app:
    build:
      context: ./sawbuck_app
      dockerfile: ./Dockerfile-installed
    image: market-sawbuck-app-installed
    container_name: market-sawbuck-app-installed
    expose:
      - 80
    ports:
      - '8041:80'
    depends_on:
      - market-rest-api

  rethink:
    image: rethinkdb:2.3
    container_name: rethink-installed
    expose:
      - 28015

  settings-tp:
    image: hyperledger/sawtooth-settings-tp
    container_name: sawtooth-settings-tp-installed
    depends_on:
      - validator
    command: settings-tp -v -C tcp://validator:4004

  validator:
    image: hyperledger/sawtooth-validator
    container_name: sawtooth-validator-installed
    expose:
      - 4004
    command: |
      bash -c "
        if [ ! -f /etc/sawtooth/keys/validator.priv ]; then
        sawadm keygen &&
        sawtooth keygen my_key &&
        sawset genesis -k /root/.sawtooth/keys/my_key.priv &&
        sawadm genesis config-genesis.batch
        fi;
        sawtooth-validator -vv \
          --endpoint tcp://validator:8800 \
          --bind component:tcp://eth0:4004 \
          --bind network:tcp://eth0:8800
      "
