# Copyright 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ------------------------------------------------------------------------------

version: '2.1'

services:
  market-shell:
    build:
      context: .
      dockerfile: ./dev_env/Dockerfile-installed
    image: market-dev-env-installed
    container_name: market-shell-installed
    depends_on:
      - market-processor
      - market-ledger-sync
      - market-rest-api
    command: tail -f /dev/null

  market-processor:
    build:
      context: .
      dockerfile: ./processor/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-tp-installed
    expose:
      - 4004
    container_name: market-tp-installed
    command: marketplace-tp -v -C tcp://localhost:4004

  market-rest-api:
    build:
      context: .
      dockerfile: ./rest_api/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-rest-api-installed
    expose:
      - 4004
      - 8000
    ports:
      - '8040:8000'
    depends_on:
      - market-ledger-sync
      - rethink
    command: |
      bash -c "
        sleep 3 &&
        marketplace-rest-api \
          --host market-rest-api \
          --db-host rethink \
          --validator tcp://localhost:4004
      "

  market-ledger-sync:
    build:
      context: .
      dockerfile: ./ledger_sync/Dockerfile-installed
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    image: market-ledger-sync-installed
    container_name: market-ledger-sync-installed
    expose:
      - 4004
    depends_on:
      - rethink
    command: |
      bash -c "
        sleep 1 &&
        market-setup-db --host rethink &&
        marketplace-ledger-sync -vv \
          --db-host rethink \
          --validator tcp://localhost:4004
      "

  market-sawbuck-app:
    build:
      context: ./sawbuck_app
      dockerfile: ./Dockerfile-installed
    image: market-sawbuck-app-installed
    container_name: market-sawbuck-app-installed
    expose:
      - 80
    ports:
      - '8041:80'
    depends_on:
      - market-rest-api

  rethink:
    image: rethinkdb:2.3
    container_name: rethink-installed
    expose:
      - 28015
